arch: amd64
language: cpp

jobs:
  include:
    - stage: "Unit tests"
      os: linux
      name: "oraclejdk8"
      script: 
        - export JAVA_HOME=$HOME/oraclejdk8
        - $TRAVIS_BUILD_DIR/install-jdk.sh --install oraclejdk8 --target $JAVA_HOME
        - java -version
        - clang++ -fPIC -O3 -shared bindings.cpp -I hnswlib -o l hnswlib-jna/src/main/resources/libhnswlib-jna.so
        - mvn test
    - stage: "Unit tests"
      name: "openjdk8"
      os: linux
      script: 
        - export JAVA_HOME=$HOME/openjdk8
        - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk8 --target $JAVA_HOME
        - java -version
        - clang++ -fPIC -O3 -shared bindings.cpp -I hnswlib -o l hnswlib-jna/src/main/resources/libhnswlib-jna.so
        - mvn test
    - stage: "Unit tests"
      name: "oraclejdk8"
      os: osx
      script: 
        - export JAVA_HOME=$HOME/oraclejdk8
        - $TRAVIS_BUILD_DIR/install-jdk.sh --install oraclejdk8 --target $JAVA_HOME
        - clang++ -std=c++11 -O3 -shared bindings.cpp -I hnswlib -o l hnswlib-jna/src/main/resources/libhnswlib-jna.dylib
        - mvn test
    - stage: "Unit tests"
      os: windows
      language: cpp
      before_install: 
        - choco install jdk8 --version 8.0.211
        - choco install maven --version 3.6.3
      script: 
        - export JAVA_HOME="/c/Program Files/Java/jdk1.8.0_211/"
        - clang++ -O3 -shared bindings.cpp -I hnswlib -o hnswlib-jna/src/main/resources/libhnswlib-jna.dll
        - /c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin/mvn test
