arch: 
  - amd64

sudo: 
 - required

language: 
  - cpp
  - java

compiler: 
  - clang

jdk: 
  - oraclejdk8

jobs:
  include:
  ####################################
    - stage: "Unit tests on linux"   #
  ####################################
      os: 
        - linux
      script: 
        - clang++ -fPIC -O3 -shared bindings.cpp -I hnswlib -o l hnswlib-jna/src/main/resources/libhnswlib-jna.so
        - mvn test
  ####################################
    - stage: "Unit tests on macos"   #
  ####################################
      os: 
        - osx
      script: 
        - clang++ -std=c++11 -O3 -shared bindings.cpp -I hnswlib -o l hnswlib-jna/src/main/resources/libhnswlib-jna.dylib
        - mvn test
  ####################################
    - stage: "Unit tests on windows" #
  ####################################
      os:
        - windows
      before_install: 
        - choco install jdk8 --version 8.0.211
        - choco install maven --version 3.6.3
      script: 
        - export JAVA_HOME="/c/Program Files/Java/jdk1.8.0_211/"
        - clang++ -O3 -shared bindings.cpp -I hnswlib -o hnswlib-jna/src/main/resources/libhnswlib-jna.dll
        - /c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin/mvn test
