arch: amd64
language: cpp
compiler: clang

jobs:
  include:
  ####################################
    - stage: "Unit tests on linux"   #
  ####################################
      os: linux
      script: 
        - java -version
        - clang++ -fPIC -O3 -shared bindings.cpp -I hnswlib -o l hnswlib-jna/src/main/resources/libhnswlib-jna.so
        - mvn test
      jdk: oraclejdk8   
      name: using oraclejdk8     
    - script: 
      - java -version
      - clang++ -fPIC -O3 -shared bindings.cpp -I hnswlib -o l hnswlib-jna/src/main/resources/libhnswlib-jna.so
      - mvn test
      jdk: openjdk8
      name: using openjdk8  
  ####################################
    - stage: "Unit tests on macos"   #
  ####################################
      os: osx
      jdk: oraclejdk8
      script: 
        - clang++ -std=c++11 -O3 -shared bindings.cpp -I hnswlib -o l hnswlib-jna/src/main/resources/libhnswlib-jna.dylib
        - mvn test
  ####################################
    - stage: "Unit tests on windows" #
  ####################################
      os: windows
      before_install: 
        - choco install jdk8 --version 8.0.211
        - choco install maven --version 3.6.3
      script: 
        - export JAVA_HOME="/c/Program Files/Java/jdk1.8.0_211/"
        - clang++ -O3 -shared bindings.cpp -I hnswlib -o hnswlib-jna/src/main/resources/libhnswlib-jna.dll
        - /c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3/bin/mvn test
